### ISSUE TITLE
Undefined message when uploading file

### ISSUE THREAD

**Issue by pzupan** [galetahub/ckeditor#829] opened 2019-01-09 18:37 UTC
I upgraded to 4.3.0 and the file upload is now not working.  When I select an image and then click "Send to Server", I get an "undefined" message.  There is no other error messages in the console or on the server.
![screenshot](https://user-images.githubusercontent.com/45881/50920440-41e83700-13fa-11e9-91a8-c6313e112589.png)

When debugging on the server, I notice that the attributes of the asset model are blank when it is saved, and it fails validation.
```
   10:   def respond_with_asset(asset)
   11:     asset_response = Ckeditor::AssetResponse.new(asset, request)
   12: 
=> 13:     if asset.save
   14:       render asset_response.success(config.relative_url_root)
   15:     else
   16:       render asset_response.errors
   17:     end
(byebug) asset
#<Ckeditor::Picture id: nil, attachable_id: nil, attachable_type: nil, asset_type: "image", description: nil, sort_by: "", visible: false, data_file_name: nil, data_content_type: nil, data_file_size: nil, deleted_at: nil, created_at: nil, updated_at: nil, row_order: nil, data_fingerprint: nil>
(byebug) 
```

**Comment by andikarekatias** [comment] 2019-01-28 15:36
i have the same problem.
i've tried uploading images by clicking on 'Browse Server' within the image info tab, But the loading wont stop.

![loading](https://user-images.githubusercontent.com/10099168/51846721-bb65ac00-234c-11e9-9216-dc0eb8f35c18.PNG)

i've tried too to drag and drop image, i got an "HTTP error occurred during file upload (error status: 422)." message.

![drag n drop](https://user-images.githubusercontent.com/10099168/51846899-1d261600-234d-11e9-99c3-53d2927ab45e.PNG)

**Comment by Hainminsoe** [comment] 2019-01-28 19:08
same Here
https://user-images.githubusercontent.com/13514657/51859838-7c445480-2366-11e9-99bb-ff088567129c.png

**Comment by Hainminsoe** [comment] 2019-01-28 21:18
SOLVED 
-----------
In my case , i was reinstalling image magic.

`sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev libmagic-dev`
`sudo apt-get install imagemagick`

Everythins is OK right now, hope this help.

**Comment by andikarekatias** [comment] 2019-01-28 22:40
My previus Version: ImageMagick 7.0.8-24 Q16 x64 2019-01-17 
after update to Version: ImageMagick 7.0.8-25 Q16 x64 2019-01-28
still not work.

**Comment by Tectract** [comment] 2019-03-14 00:45
Hi guys, I just set up CKEditor for the first time, fresh install following this tutorial:

https://richonrails.com/articles/getting-started-with-ckeditor

Neither "send it to server" from the image->upload tab nor "upload" button within the "ckeditor file manager" work, I cannot add ANY images to any articles, under this fresh ckeditor installation.

    sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev libmagic-dev
    sudo apt-get install imagemagick

This did NOT fix the isssue for me. Is there any workaround or known cause? Can I go back to a lower version of CKEditor and maybe it will work?

imagemagick (8:6.7.7.10-6ubuntu3.13)
ckeditor (4.3.0)
paperclip (6.1.0)
rails 4.2.10
ruby 2.4.5

**Comment by Tectract** [comment] 2019-03-14 00:47
here's some output from the rails logs that may be useful:

> Started POST "/ckeditor/pictures?qqfile=Zion_national_park.jpg" for 127.0.0.1 at 2019-03-13 18:33:11 -0600
Processing by Ckeditor::PicturesController#create as */*
  Parameters: {"qqfile"=>"Zion_national_park.jpg"}
  User Load (0.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
request at : http://localhost:3000/ckeditor/pictures?qqfile=Zion_national_park.jpg
>  user_signed_in? : true
[paperclip] Trying to link /tmp/95858f92392a00477aca698acc3443e7607517c720190313-12032-7l1x1i to /tmp/320d3652628d120cff0bd1d8a7d6079720190313-12032-1ux1i3s.jpg
[paperclip] Trying to link /tmp/320d3652628d120cff0bd1d8a7d6079720190313-12032-1ux1i3s.jpg to /tmp/320d3652628d120cff0bd1d8a7d6079720190313-12032-1b03qb1.jpg
Command :: file -b --mime '/tmp/320d3652628d120cff0bd1d8a7d6079720190313-12032-1b03qb1.jpg'
   (0.2ms)  BEGIN
[paperclip] Trying to link /tmp/320d3652628d120cff0bd1d8a7d6079720190313-12032-1ux1i3s.jpg to /tmp/320d3652628d120cff0bd1d8a7d6079720190313-12032-1uyzqpy.jpg
Command :: file -b --mime '/tmp/320d3652628d120cff0bd1d8a7d6079720190313-12032-1uyzqpy.jpg'
   (0.2ms)  ROLLBACK
Completed 200 OK in 148ms (Views: 10.2ms | ActiveRecord: 1.3ms)

**Comment by Tectract** [comment] 2019-03-14 00:57
the above response was when I tried the "upload" button. Here is the response when I try the "send it to server" button (below). Note they both end in ROLLBACK, oops!

> Started POST "/ckeditor/pictures" for 127.0.0.1 at 2019-03->13 18:55:29 -0600
Processing by Ckeditor::PicturesController#create as */*
  Parameters: {"upload"=>#<ActionDispatch::Http::UploadedFile:0x000000000df00228 @tempfile=#<Tempfile:/tmp/RackMultipart20190313-17968-mfm92q.jpg>, @original_filename="Zion_national_park.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"upload\"; filename=\"Zion_national_park.jpg\"\r\nContent-Type: image/jpeg\r\n">, "ckCsrfToken"=>"YZyfZUI10bhQWp67X12xBv25lbPW05OWL4qEMFY1"}
  User Load (0.3ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1  ORDER BY "users"."id" ASC LIMIT 1  [["id", 2]]
request at : http://localhost:3000/ckeditor/pictures
> user_signed_in? : true
   (0.1ms)  BEGIN
   (0.2ms)  ROLLBACK
Completed 200 OK in 9ms (Views: 0.3ms | ActiveRecord: 0.6ms)

**Comment by Tectract** [comment] 2019-03-14 01:26
looks like for me the temporary work-around was to downgrade versions to gem 'ckeditor', '~> 4.1.3'

then I needed to rollback the paperclip migrate, redo it, forcing file overwrites...

Great plugin BTW hope you can nail this bug! Cheers~

**Comment by jarongao** [comment] 2019-05-01 14:02
A coworker believes this issue is caused by https://github.com/galetahub/ckeditor/commit/b8adc36afc995bed03064d093a24d096104df3d7

**Comment by jmchaves** [comment] 2019-05-09 16:22
I found a solution here:
https://stackoverflow.com/questions/54272909/ckeditor-upload-image-error-undefined-index-ckeditorfuncnum

**Comment by jarongao** [comment] 2019-05-09 16:26
If you're using 'ckeditor' 4.3 gem with 4.11 JS lib, then you should use `config.filebrowserUploadMethod = 'form';`

**Comment by Tectract** [comment] 2019-05-09 17:34
Great catch guys. Can one of you test it and submit a PR bugfix?

**Comment by r3cha** [comment] 2019-05-10 22:35
@jarongao Thanks, I see that problem was when you use newer version of Ckeditor like 4.11.3 and this version send filed as blob not form multipart and this is seems like bug in Ckeditor that change default behaviour of uploader and not fix default success request handler?

**Comment by Tectract** [comment] 2019-05-11 06:44
I'm currently version-locked to a lower version of ckeditor because of the file upload not working bug. I'd say this is high priority, if anyone is actively working on this project.

**Comment by r3cha** [comment] 2019-05-11 10:56
@Tectract You mean working on creditor? I'm not sure but think fix should be on Ckeditor like they change default behaviour of uploader but not did same for srcipt that handle this success request. I checkout his repos and they have a lot of) https://github.com/ckeditor for different frameworks.

**Comment by Tectract** [comment] 2019-05-11 19:41
What I mean is that when I tried to install CKEditor, last month, I couldn't use the most recent version because image uploading is COMPLETELY BROKEN, so I am version-locked to a lower version where image loading still worked. As far as I'm concerned, the most recent release version is broken, and was released prematurely without proper testing, and needs critical care fixing, of this specific issue. Just my two cent.

**Comment by jarongao** [comment] 2019-05-11 23:54
Our QA team has tested the new config setting in config.js and confirms that Image Uploading works as in version 4.2.4. I'll submit a PR to update the default config script.

**Comment by yash-react-ror-developer** [comment] 2019-05-14 07:29
> I found a solution and it worked for me:
> https://stackoverflow.com/questions/54272909/ckeditor-upload-image-error-undefined-index-ckeditorfuncnum

Thanks, It works

**Comment by yash-react-ror-developer** [comment] 2019-05-14 07:30
> I found a solution and it worked for me:
> https://stackoverflow.com/questions/54272909/ckeditor-upload-image-error-undefined-index-ckeditorfuncnum

**Comment by Tectract** [comment] 2019-05-14 17:50
I'm currently locked on gem versino 4.1.3 because of this bug.

> gem 'ckeditor', '~> 4.1.3'

Is there anything special I will need to do to upgrade to the latest version, once the "image uploading bug" is confirmed fixed?

**Comment by kevinhq** [comment] 2019-05-23 10:18
This https://github.com/galetahub/ckeditor/pull/847/commits/ee605605bbd35b1f331a68e60435b6479d7dbac4 solved for me.

Using ckeditor 4.3.0.
For those who did not want to upgrade to latest version (or were unable to), just apply that change on your own app/asssets/javascripts/ckeditor/config.js

**Comment by jarongao** [comment] 2019-05-23 22:14
@Tectract, see previous comment https://github.com/galetahub/ckeditor/issues/829#issuecomment-495159213 that references my merged PR https://github.com/galetahub/ckeditor/commit/ee605605bbd35b1f331a68e60435b6479d7dbac4.

You can upgrade to gem version `4.3.0` and update your `config.js` with that line to have Image Uploads work.

**Comment by Tectract** [comment] 2019-05-23 22:52
thank you I will test soon and report back if anything goes wrong :)

**Comment by man1400** [comment] 2019-06-26 11:44
I upgraded to 4.11.4 and the file upload is now not working. When I select an image and then click "Send to Server", I get an "undefined" message. There is no other error messages in the console or on the server.

![image](https://user-images.githubusercontent.com/52243066/60177120-521b9380-982d-11e9-8b86-b884d35592fd.png)

**Comment by jarongao** [comment] 2019-06-26 11:57
@man1400 https://github.com/galetahub/ckeditor/issues/829#issuecomment-490973673

**Comment by Tectract** [comment] 2019-08-25 12:09
I was able to upgrade to Rails 5.2.3 but only got CKEditor up to version 4.2.2 working. I was not able to get CKEditor working in Rails 5.2.3 at the latest version, and it had something to do with the change in the way the init routine is called, no longer included in config/application.rb?

**Comment by Tectract** [comment] 2019-08-25 12:11
Also, I included in my app/assets/javascripts/ckeditor/config.js this line:

  config.filebrowserUploadMethod = 'form';

not sure if that is actually required, but maybe it should be in the default config so we don't have to include it manually, or more of a note about that in the README?

**Comment by Tectract** [comment] 2019-08-25 12:12
also, stalebot sucks. Issues should remain open until they are RESOLVED.

**Comment by marvindpunongbayan** [comment] 2019-09-06 13:13
We encounter this issue after upgrading from 4.1.6 to 4.3.0.

And then, when I put this line:
`config.filebrowserUploadMethod = 'form';`

We encounter a different issue. 

Here's the sample:
`Started POST "/ckeditor/pictures?CKEditor=lesson_description&CKEditorFuncNum=67&langCode=en&authenticity_token=yFd3mxekrjEa4%2FxgPNhopYeC65i%2Fcul%2B6QysKDJNnQk%3D" for 127.0.0.1 at 2019-09-06 20:31:27 +0800
Processing by Ckeditor::PicturesController#create as HTML
  Parameters: {"upload"=>#<ActionDispatch::Http::UploadedFile:0x007fe54d9c84e0 @tempfile=#<Tempfile:/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/RackMultipart20190906-58297-1y5xzw4>, @original_filename="Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-18.png", @content_type="image/png", @headers="Content-Disposition: form-data; name=\"upload\"; filename=\"Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-18.png\"\r\nContent-Type: image/png\r\n">, "ckCsrfToken"=>"SB7EX34CHeNrXFveJOv7gzkc1CG6h1owBzs5Pdr3", "CKEditor"=>"lesson_description", "CKEditorFuncNum"=>"67", "langCode"=>"en", "authenticity_token"=>"yFd3mxekrjEa4/xgPNhopYeC65i/cul+6QysKDJNnQk="}
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Command :: identify -format %m '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Command :: identify -format %m '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Command :: identify -format %m '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Command :: convert '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]' -auto-orient -resize "800>" '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w15920190906-58297-m4891c'
Command :: file -b --mime '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w15920190906-58297-m4891c'
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Command :: identify -format %m '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Command :: identify -format %m '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Command :: identify -format %m '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Command :: convert '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]' -auto-orient -resize "118x" -crop "118x100+0+45" +repage '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w15920190906-58297-42xa18'
Command :: file -b --mime '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w15920190906-58297-42xa18'
Command :: identify -format '%wx%h,%[exif:orientation]' '/var/folders/7r/12vhpprs3xv6st6ymr4kx_3r0000gn/T/Inbox (58,985 messages, 2 unread) 2019-08-15 21-55-1820190906-58297-102w159.png[0]'
Completed 500 Internal Server Error in 576ms

ActionView::MissingTemplate - Missing template ckeditor/pictures/create, ckeditor/application/create, application/create with {:locale=>[:en], :formats=>[:html], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :jbuilder, :haml]}. Searched in:
  * "/Users/marvinpunongbayan/Documents/lms-app/app/views"
  * "/Users/marvinpunongbayan/.rvm/gems/ruby-2.1.2@lms-app/gems/simple_calendar-2.2.7/app/views"
  * "/Users/marvinpunongbayan/.rvm/gems/ruby-2.1.2@lms-app/bundler/gems/rails_db-4a0971a1aa0a/app/views"
  * "/Users/marvinpunongbayan/.rvm/gems/ruby-2.1.2@lms-app/gems/kaminari-bootstrap-3.0.1/app/views"
  * "/Users/marvinpunongbayan/.rvm/gems/ruby-2.1.2@lms-app/gems/kaminari-0.15.1/app/views"
  * "/Users/marvinpunongbayan/.rvm/gems/ruby-2.1.2@lms-app/gems/devise_invitable-1.3.0/app/views"
  * "/Users/marvinpunongbayan/.rvm/gems/ruby-2.1.2@lms-app/gems/devise-3.2.4/app/views"
  * "/Users/marvinpunongbayan/.rvm/gems/ruby-2.1.2@lms-app/gems/ckeditor-4.3.0/app/views"
:`

Is there anything I should add or change to my ckeditor/config?

**Comment by marvindpunongbayan** [comment] 2019-09-06 13:32
I made it work without this line
``
config.filebrowserUploadMethod = 'form';``

I just change this from my ckeditor/config:
``
From: config.filebrowserImageUploadUrl = "/ckeditor/pictures?";
``
To: config.filebrowserImageUploadUrl = "/ckeditor/pictures?command=QuickUpload&type=Images";

**Comment by marvindpunongbayan** [comment] 2019-09-06 13:37
I encounter the same problem after upgrading my Ckeditor from 4.1.6 to 4.3.0.

And I solved the problem from my end without adding this line:
``
config.filebrowserUploadMethod = 'form';``

I just change this line from my OLD custom ckeditor/config:
**From:** ``config.filebrowserImageUploadUrl = "/ckeditor/pictures?";``

**To:** ``config.filebrowserImageUploadUrl = "/ckeditor/pictures?command=QuickUpload&type=Images";``

**Comment by Tectract** [comment] 2019-11-05 15:09
stalebot is a virus

**Closed** 2020-01-11 16:43 UTC
Labels: bug, wontfix

**Comment by asecondwill** [comment] 2021-04-09 12:48
@marvindpunongbayan  - worked for me  - thanks.

**Comment by ufukcicekdev** [comment] 2023-09-01 11:31
Hello,
When I send to server I get undefined error. but the solutions written here did not work for me. . is there anyone who still has this problem and found a solution?
