### ISSUE TITLE
editor ads \r\n\t\t\t

### ISSUE THREAD

**Issue by proigor** [galetahub/ckeditor#807] opened 2018-05-18 06:24 UTC
Hi!

For some reasons ckeditor adds \r\n\t\t\t when I have "Single<br/>line" text.
So in output it's "Single<br/>\r\n\t\t\tline".
I saw "FormatOutput" suggestion in google, but looks like it's old option.

Any advice much appreciated.

**Comment by patricklindsay** [comment] 2018-12-04 08:35
Closing this, if you're still having the issue feel free to reopen with a test case/example app reproducing the issue. May want to also test this out using a demo Ckeditor on the official website to check where the issue is originating from

**Closed by patricklindsay** 2018-12-04 08:35 UTC

**Comment by simonbrazell** [comment] 2019-06-13 04:31
Add this to the editor `config.js` file:
```
CKEDITOR.editorConfig = config => {
  ...
}

CKEDITOR.on('instanceReady', function (ev) {
  var blockTags = ['div', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'p', 'pre', 'li', 'blockquote', 'ul', 'ol',
    'table', 'thead', 'tbody', 'tfoot', 'td', 'th',];

  for (var i = 0; i < blockTags.length; i++) {
    ev.editor.dataProcessor.writer.setRules(blockTags[i], {
      indent: false,
      breakBeforeOpen: false,
      breakAfterOpen: false,
      breakBeforeClose: false,
      breakAfterClose: false
    });
  }
});
```
This makes it so line breaks are no longer inserted, and can be edited as you see fit.
