### ISSUE TITLE
Seed content with images

### ISSUE THREAD

**Issue by mgtf** [galetahub/ckeditor#434] opened 2014-04-07 12:23 UTC
Dear all,
I'm trying to import articles from old storage and i want pictures which are in articles be stored using carrierwave and i want to be able to see this pictures in ckeditor file manager later when editing articles. 

The code below works fine but the little problem is that I have to manually set picture model ID so that CkeditorPictureUploader can create correct path (something like :     "ckeditor/pictures/#{model.id}"). If i dont set CkeditorPictureUploader instance ID, then #{model.id} is nil so that all pictures are stored in the same "ckeditor/pictures/" folder.
Is there a better way to achieve this please ?

```
    # code from my db/seed.rb
    # Store article images to S3 using carrierwave
    # body contains the article XML (nokogiri)
    body.css("img").each do |img|
      src = img['src']
      uri = URI.parse(src)
      filename = File.basename(uri.path)
      next if(File.extname(filename) == '.php')
      File.open("tmp/" << filename, 'wb+') do |f|
        f.write HTTParty.get(src).parsed_response
        image = Ckeditor.picture_model.new
        # Have to manually set model.id
        image.id = Ckeditor.picture_model.last.nil? ? 1 : Ckeditor.picture_model.last.id + 1
        image.data.store!(f)
        image.save
        img['src'] = image.data.url
      end
    end
```

**Comment by kyledecot** [comment] 2015-06-24 11:03
As this is more of a question and not a bug report I'm going to go ahead and close this. I suggest that you post this on StackOverflow if you haven't done so already.

**Closed by kyledecot** 2015-06-24 11:03 UTC
